= Change Log
:toc:

== Version 1.3.0 (Feb 12, 2017)

* Split the configuration of authentication into a separate screen
(https://issues.jenkins-ci.org/browse/JENKINS-35081[JENKINS-35081])
 ** See
https://wiki.jenkins.io/display/JENKINS/Authorize+Project+plugin#AuthorizeProjectplugin-Screenshots[#Screenshots]
for details.

== Version 1.2.2 (May 28, 2016)

* Fixed: Builds aren't start when security realm fail to find the user
for authorization (e.g. Bind DN is not set for Active Directory
plugin)
(https://issues.jenkins-ci.org/browse/JENKINS-34279[JENKINS-34279])

== Version 1.2.1 (Apr 03, 2016)

* Fixed: password / api token fields for "Run as Specific User" are
broken
https://issues.jenkins-ci.org/browse/JENKINS-33897[JENKINS-33897]

== Version 1.2.0 (Mar 27, 2016)

* *Targets Jenkins 1.625*
* SECURITY FIX: Reject unauthenticated configurations via REST / CLI
(https://issues.jenkins-ci.org/browse/JENKINS-28298[JENKINS-28298])
 ** See
https://wiki.jenkins.io/display/JENKINS/JENKINS-28298[JENKINS-28298]
for details.
* Support global default authorization strategy
(https://issues.jenkins-ci.org/browse/JENKINS-30574[JENKINS-30574])
* Displays an error when a built-in user is used for "Run as Specific
User"
(https://issues.jenkins-ci.org/browse/JENKINS-32769[JENKINS-32769])
* Added "Run as SYSTEM"
(https://issues.jenkins-ci.org/browse/JENKINS-32770[JENKINS-32770])
 ** Disabled by default for projects. You have to enable it in the
global security configuration page.

== Version 1.1.0 (Aug 9, 2015)

* Added a feature to enable / disable strategies.
(https://issues.jenkins-ci.org/browse/JENKINS-28298[JENKINS-28298])
 ** *"Run as Specific User" is disabled by default. You need to
enable it after upgrading from a prior version if you use it.*
* Supports workflow
(https://issues.jenkins-ci.org/browse/JENKINS-26670[JENKINS-26670])
* Supports apitoken for authentication.
(https://issues.jenkins-ci.org/browse/JENKINS-22470[JENKINS-22470])
* Add support for upcoming $class annotation change
(https://issues.jenkins-ci.org/browse/JENKINS-25403[JENKINS-25403])

== Version 1.0.3 (Apr 14, 2014)

* *SECURITY FIX*: Authentication of "Run as Specific User" is easily
bypassed by REST/CLIadded (Fixed
https://issues.jenkins-ci.org/browse/JENKINS-22469[JENKINS-22469])
* Replaced radio buttons to dropdown selecting authorization
strategies (Fixed
https://issues.jenkins-ci.org/browse/JENKINS-20786[JENKINS-20786])

== Version 1.0.2 (Feb 22, 2014)

* added `AuthorizeProjectStrategyDescriptor`
https://issues.jenkins-ci.org/browse/JENKINS-20812[JENKINS-20812]
* Not to send the password value to test whether password is required.

== Version 1.0.1 (Nov 30, 2013)

* Fix a problem that a new user created if you authenticate with
non-existent user (Fix
https://issues.jenkins-ci.org/browse/JENKINS-20784[JENKINS-20784])
* Works with MatrixProject (Fix
https://issues.jenkins-ci.org/browse/JENKINS-20785[JENKINS-20785])

== Version 1.0.0 (Nov 24, 2013)

* Initial release.
